# name: Vercel Production Deployment

# on:
#   push:
#     branches: [ master ]

# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Compile SCSS
#         uses: peter-evans/repository-dispatch@v2
#         with:
#           event-type: trigger-scss-compilation
#           token: ${{ secrets.ACTIONS_KEY }}
#           repository: ${{ github.repository }}
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

#       - uses: actions/checkout@v3
#         with:
#           ref: vercel-deploy

#       - name: Install Vercel CLI
#         run: |
#           npm install --global vercel@latest

#       - name: Pull Vercel environment info
#         run: |
#           vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Build project artifacts
#         run: |
#           vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Deploy project artifacts to Vercel
#         run: |
#           vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
